---
# tasks file for ansible-role-mantis
  - name: Ajouter php7 à sourcelist
    apt_repository:
      repo: "{{ php_repo }}"
      state: present
      filename: php
      update_cache: no

  - name: Récupérer le clé gpg
    apt_key:
      url: "{{ php_key }}"

  - name: Apt fix
    shell: apt -y --fix-broken install

  - name: Maj des paquets
    apt:
      update_cache: yes
      upgrade: 'yes'

  - name: Installation de "{{ paquets_webapp }}"
    apt:
      name: "{{item }}"
      state: latest
    loop: "{{ paquets_webapp }}"

  - name: Téléchargement de Mantis
    get_url:
      url: https://sourceforge.net/projects/mantisbt/files/mantis-stable/2.23.0/mantisbt-2.23.0.tar.gz
      dest: ~/
    notify: Installation mantis

  - name: Déclencher les handlers
    meta: flush_handlers

  - name: Créer VirtualHost
    template:
      src: mantisbt.conf.j2
      dest: /etc/apache2/sites-available/mantisbt.conf
    notify: Relancer apache

  - name: Lancer Apache
    service: 
      name: apache2 
      state: started